
class Company_locators():

    companies_xpath = "//a[normalize-space()='Companies']"
    addcompany_xpath = "//a[normalize-space()='Add Company']"
    Company_name_xpath = "//input[@id='CompanyName']"
    Description_xpath = "//textarea[@name='Description']"
    Country_xpath = "//input[@id='country']"
    Building_name_xpath = "//input[@id='Building']"
    Street_name_xpath = "//input[@id='Street']"
    Suburb_xpath = "//input[@id='city']"
    State_xpath = "//input[@id='state']"
    Postal_code_xpath = "//input[@id='postalcode']"
    Contact_number_xpath = "//input[@id='Contact']"
    Email_xpath = "//input[@id='Email']"
    Return_Portal_Domain_xpath = "//input[@id='CustomDomain']"
    Site_Url_xpath = "//input[@id='SiteURL']"
    Submit_button_xpath = "//button[normalize-space()='Submit']"
    export_button_xpath = "//button[@id='export_booking']"
    company_change_logo_xpath = "//a[normalize-space()='Company Change Log']"
    Company_search_button_xpath = "//span[@id='select2-CompanyId-container']"
    Search_Test_Return_xpath = "/html[1]/body[1]/span[1]/span[1]/span[2]/ul[1]/li[67]"
    Change_type_field_xpath = "//span[@id='select2-ChangesType-container']"
    Add_type_xpath = "/html[1]/body[1]/span[1]/span[1]/span[2]/ul[1]/li[2]"
    start_date_xpath = ""
    search_button_xpath = "//button[normalize-space()='Search']"
    Click_popup_xpath = "//i[@class='fa fa-search']"
    click_cross_button = "//button[normalize-space()='×']"
    View_companies_xpath = "//a[normalize-space()='View Companies']"
    Search_field_xpath = "//input[@id='search']"
    Test_return_xpath = "/html[1]/body[1]/span[1]/span[1]/span[2]/ul[1]/li[68]"
    Search_button_xpath = "//button[normalize-space()='Search']"
    edit_xpath = "//a[normalize-space()='Edit']"
    update_button_xpath = "//button[normalize-space()='Update']"
    update_type_xpath = "/html[1]/body[1]/span[1]/span[1]/span[2]/ul[1]/li[3]"
