class Hub_locators():
    hub_button_xpath = "//a[normalize-space()='Hub']"
    add_hub_button_xpath = "//a[normalize-space()='Add Hub']"
    hub_company_name_xpath = "// select[@id='CompanyId']"
    company_hub_test_return_xpath = "//option[@value='34'][normalize-space()='Test Return']"
    name_xpath = "//input[@id='Name']"
    description_xpath = "//input[@id='description']"
    Building_xpath = "//input[@id='BuildingName']"
    Address_street_xpath = "//input[@id='StreetAddress']"
    Country_xpath = "//input[@id='country']"
    suburub_xpath = "//input[@id='city']"
    city_xpath = "//input[@id='state']"
    postcode_xpath = "//input[@id='postalcode']"
    email_xpath = "//input[@id='Email']"
    serviceable_countries_xpath = "/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/section[1]/div[2]/div[1]"
    submit_xpath = "//button[normalize-space()='Submit']"
